.TH WICD-CLIENT "1" "September 2008" "wicd-client " "User Commands"
.SH NAME
wicd-client \- manual page for wicd-client 
.SH DESCRIPTION
wireless (and wired) connection daemon front\-end.
.SS "Arguments:"
.TP
\fB\-n\fR      \fB\-\-no\-tray\fR
Run wicd without the tray icon.
.TP
\fB\-h\fR      \fB\-\-help\fR
Print this help information.
.TP
\fB\-a\fR      \fB\-\-no\-animate\fR
Run the tray without network traffic tray animations.
