#!/bin/sh

# Stop daemon
if [ -f /etc/init.d/wicd ]; then
  /etc/init.d/wicd stop
fi
  
# Remove Wicd from the boot sequence
if which update-rc.d &>/dev/null ; then
  update-rc.d -f wicd remove
fi

# Remove pyc files 
# They may exist if you are upgrading Wicd
rm -f /opt/wicd/*.pyc

# Add Wicd to the startup sequence
# 80 to make sure that dbus is running when Wicd starts
if which update-rc.d &>/dev/null ; then
  update-rc.d wicd start 80 2 3 4 5 . stop 20 0 1 6 .
fi

# Start the daemon
if [ -f /etc/init.d/wicd ]; then
  /etc/init.d/wicd start
fi
