#!/bin/sh
#stop daemon!
/etc/init.d/wicd stop

#remove because we changed stuff
update-rc.d -f wicd remove

#remove pyc files that screw things up sometimes
#there shouldn't be any there, but it never hurts to check
#they may exist if you are upgrading wicd
rm -rf /opt/wicd/*.pyc

#add us to the startup
#add us to 80 because sometimes dbus starts
#later then 20, so that causes problems
update-rc.d wicd start 80 2 3 4 5 . stop 20 0 1 6 .

#start the daemon
/etc/init.d/wicd start
