#!/bin/bash

# borrowed from
# http://repos.archlinux.org/viewvc.cgi/wicd/repos/extra-i686/wicd-daemon?revision=1&view=markup
# and modified for 1.5.0

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Starting wicd Daemon"
    killall wicd &> /dev/null
    /usr/sbin/wicd-daemon &> /dev/null
    add_daemon wicd
    stat_done
    ;;
  stop)
    stat_busy "Stopping wicd Daemon"
    killall wicd &> /dev/null
    rm_daemon wicd
    stat_done
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0

