.TH WICD-CLIENT "1" "June 2009"
.SH NAME
wicd-client \- frontend voor de WICD daemon
.SH BESCHRIJVING
draadloos (en vast) verbindingen daemon front\-end.

Als \fBwicd-curses\fR is geïnstalleerd en je probeert wicd-client uit te voeren
zonder een actieve X server in de huidige terminal, wicd-client probeert
\fBwicd-curses\fR in plaats daarvan te starten. Hij zal je waarschuwen als dit de
eerste keer gebeurt.
.SH OPTIES
.TP
.B \-n, \-\-no\-tray
Start Wicd zonder het tray icon.
.TP
.B \-h, \-\-help
Print deze helptekst.
.TP
.B \-a, \-\-no\-animate
Start de tray icon zonder netwerkgebruik animaties.
.SH ZIE OOK
.BR wicd-curses (8)
.BR wicd (8)
