#! /bin/sh
#
# wicd        wicd daemon
#                               Daemon for managing network connections.
#                               This file should be placed in /etc/init.d.
#
# Authors:      Dan O'Reilly <oreilldf@gmail.com>
#
# Version:      @(#)skeleton  2.85-23  28-Jul-2004  miquels@cistron.nl
#

set -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="Network connection manager daemon"
NAME="wicd"
PROCNAME=wicd-daemon
DAEMON=/opt/wicd/daemon.py
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
USER=root

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

#
#       Function that starts the daemon/service.
#
d_start() {
        start-stop-daemon --start --quiet --pidfile $PIDFILE \
                --user $USER --exec $DAEMON -- $DAEMON_OPTS
}

#
#       Function that stops the daemon/service.
#
d_stop() {
        start-stop-daemon --stop --quiet --pidfile $PIDFILE \
                 --oknodo --user $USER --name $PROCNAME
}


case "$1" in
  start)
        echo -n "Starting $NAME:"
        d_start
        echo " Done."
        ;;
  stop)
        echo -n "Stopping $NAME:"
        d_stop
        echo " Done."
        ;;
  restart|force-reload)
        echo -n "Restarting $NAME:"
        d_stop
        sleep 1
        d_start
        echo " Done."
        ;;
  *)
        echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0

